# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigIntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('weight', models.BigIntegerField()),
                ('height', models.BigIntegerField()),
                ('width', models.BigIntegerField()),
                ('length', models.BigIntegerField()),
                ('location_from', models.CharField(max_length=200)),
                ('location_to', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
